### ISSUE TITLE
建议使用alpine基础镜像，比如：7.4-alpine

### ISSUE THREAD

**Issue by wzhih** [swoole/docker-swoole#13]
建议使用`alpine`基础镜像，比如：`7.4-alpine`

`alpine`基础镜像小很多(80M)，生成的`swoole`镜像也会小很多

**Comment by deminy** [comment]
Thanks for the suggestion. It's in [our TODO list](https://github.com/swoole/docker-swoole#todos); unfortunately we won't have any resource or time working on it in the coming months.
