### ISSUE TITLE
AUTORELOAD_ANY_FILES

### ISSUE THREAD

**Issue by galliroberto** [swoole/docker-swoole#15]
Good morning,
I have setted AUTORELOAD_ANY_FILES=1
but hot reload not work.

I use symfony with https://github.com/k911/swoole-bundle
i have installed inotify, but when i change php file, the change is not reflected.

**Comment by deminy** [comment]
I don't have much background information for your case, but my guess is that it could be one of the two reasons:

1. Missing option "**autorestart = true**" in the Supervisor configuration file.

If your Supervisor configuration file look like this,

```ini
[supervisord]
user = root

[program:symfony]
command = ./bin/console swoole:server:run
user = root
autostart = true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/1
stderr_logfile_maxbytes=0
```

please consider to change it to:

```ini
[supervisord]
user = root

[program:symfony]
command = ./bin/console swoole:server:run
user = root
autostart = true
autorestart = true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/1
stderr_logfile_maxbytes=0
```

2. There could be too many files under your working directory, which excceeds the limit of the autoloading program _inotify_. If that's the case, please follow my answer [here](https://github.com/swoole/docker-swoole/issues/14#issuecomment-637944151) to increase the limit.
