### ISSUE TITLE
Run example.sh command throw error.

### ISSUE THREAD

**Issue by tubitzee** [swoole/docker-swoole#16]
When i tried to run an example command, e.g., './bin/example.sh start 01 ' , i had got an error message like that.

> find: warning: you have specified the -depth option after a non-option argument -type, but options are not positional (-depth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
find: paths must precede expression: `1'

When i had replaced file ./bin/example.sh line 20 `find examples -type d -depth 1 -name "${2}-*"`   with `find examples -type d -name "${2}-*"` , it worked.

**Comment by deminy** [comment]
Please pull latest code from the `master` branch and try again.

**Comment by tubitzee** [comment]
Thank your very much.
