### ISSUE TITLE
When I'am getting phpswoole/swoole:php8.0 Docker image I got Alpine image instead Debian

### ISSUE THREAD

**Issue by texnicii** [swoole/docker-swoole#22]
Part of my Dockerfile:
```
FROM phpswoole/swoole:php8.0
RUN apt-get update
```
Error: apt-get not found (because it is Alpine version)
![image](https://user-images.githubusercontent.com/1362140/104727083-cbe3dc80-5745-11eb-9bc5-487c76037e85.png)

**Comment by deminy** [comment]
I had manually triggered a job having image `phpswoole/swoole:php8.0` (and few other PHP 7 images)  built correctly, and just committed a code fix for it.

Thanks for reporting the issue!
