### ISSUE TITLE
docker build 报错！

### ISSUE THREAD

**Issue by ximenhuangguaduo** [swoole/docker-swoole#24]
=> ERROR [2/4] COPY ./rootfilesystem/ /                                                         0.0s
------
 > [2/4] COPY ./rootfilesystem/ /:
------
failed to compute cache key: "/rootfilesystem" not found: not found

**Comment by deminy** [comment]
Did you run the `docker build` command under **the root directory of the repository**?

As mentioned in file `README.md`, the `docker build` command should look similar to:

```bash
docker build -t phpswoole/swoole -f dockerfiles/latest/php8.0/cli/Dockerfile .
```
