### ISSUE TITLE
Suggest adding some common extensions to become more usable out of the box

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/docker-swoole#33]
For example: redis, pdo_mysql, gd, etc.

![image](https://user-images.githubusercontent.com/20104656/187572826-72e4a3c7-d980-43be-9b69-7afebedf6973.png)

![image](https://user-images.githubusercontent.com/20104656/187572838-0685bf0e-14c7-4fe8-8a7b-046a5a4625d9.png)

**Comment by liulyn** [comment]
邮件已收到 谢谢！

**Comment by XiaoHai-Xie** [comment]
So

**Comment by deminy** [comment]
Thanks for the suggestion. Extension _redis_ and _pdo_mysql_ have been added to the nightly images (built daily using the latest code of Swoole):

```bash
docker run --rm -ti phpswoole/swoole:php8.0 php --ri pdo_mysql
# ...
docker run --rm -ti phpswoole/swoole:php8.2 php --ri redis
```

The two extensions won't be added to existing version-based images (e.g., 4.8.11 and 5.0.0), but they will be added to new images (4.8.12+ and 5.0.1+).

If you want to add the two extensions manually to an existing image, you can update the Dockerfile like this:

```Dockerfile
RUN \
    set -ex && \
    docker-php-ext-install pdo_mysql && \
    pecl channel-update pecl.php.net && \
    pecl install --configureoptions 'enable-redis-igbinary="no" enable-redis-lzf="no" enable-redis-zstd="no"' redis-stable && \
    docker-php-ext-enable redis
```

**Comment by liulyn** [comment]
邮件已收到 谢谢！

**Comment by XhmikosR** [comment]
Note that this was a breaking changefor us. Doctrine relies on Redis for caching on production, but we didn't have it installed (on purpose). When the docker image was updated to 4.8.12, Doctrine started throwing errors because it did see the Redis extension and no Redis present.

We have disabled the extension, still, it'd be nice to follow some kind of semver here. If this was made in v4.9 or bigger, it wouldn't have affected us.

**Comment by deminy** [comment]
Thanks for the feedback, and sorry for the inconvenience.

I agree that we shouldn't introduce backward-incompatible changes in minor versions of the images. However, there were a few reasons why I added the two extensions in the Docker images starting from 4.8.12+ and 5.0.1+:

* We want to make it easy for people to start playing with Swoole.
* Both Redis and PDO_MySQL are popular PHP extensions, especially for Swoole users.
* Swoole 5.0.0 had been out, and the 5.0.0 Docker image was released without Redis nor PDO_MySQL included.

Thus, we either have to wait until Swoole 6.0 is out (which is not in plan yet), or keep making it difficult for those who want to use Redis/PDO_MySQL in the Swoole images.

Thus, I made a hard decision to make this backward-incompatible change and included the details in the README and CHANGELOG files. It benefits new users but could cause problems for existing users. I will add instructions on how to disable/remove the two extensions.

On my side, I will avoid making it happen again. Thanks

**Comment by XhmikosR** [comment]
Just to clarify, if you did the change in a minor version, it'd be OK too, since the new image would have affected less users. I personally use the minor version tag so that I get patch fixes and reduce the chances for something to break.

Thanks for the reply!
