### ISSUE TITLE
Alpine 3.16 Update

### ISSUE THREAD

**Issue by flexchar** [swoole/docker-swoole#36]
Is there a particular reason why alpine docker files use `php:8.1.8-cli-alpine3.15` image? 

I could propose a PR with 3.16 version.

**Comment by deminy** [comment]
Thanks for the suggestion. I added two commits today to update latest images to use Alpine 3.16, and included you as a co-author of the commits, as you can see from commit messages.

Please note that the change applies to latest images and future images (Swoole 5.0.1+ images), but not existing images.
