### ISSUE TITLE
Support for http2

### ISSUE THREAD

**Issue by oltreseba** [swoole/docker-swoole#39]
It looks like http2 is not enabled in the build (https://openswoole.com/docs/modules/swoole-http-server/configuration#open_http2_protocol). Is there a way to activate it later? Could it be included in the build?

**Comment by liulyn** [comment]
邮件已收到 谢谢！

**Comment by deminy** [comment]
Hi there. HTTP2 is always enabled in the images.

```bash
docker run --rm phpswoole/swoole:4.7 php --ri swoole | grep http2
docker run --rm phpswoole/swoole:4.8 php --ri swoole | grep http2
docker run --rm phpswoole/swoole:5.0 php --ri swoole | grep http2
```
