### ISSUE TITLE
The file is repaired locally. Automatic loading cannot take effect

### ISSUE THREAD

**Issue by yeweiliang95** [swoole/docker-swoole#41]
Using 00-autoreload deployment, the changes do not take effect after files are modified in the local directory, but can take effect inside the docker container.
![image](https://github.com/swoole/docker-swoole/assets/42090953/22892b94-41f7-4bbf-a76b-ad7d6f81705b)

**Comment by liulyn** [comment]
邮件已收到 谢谢！

**Comment by yeweiliang95** [comment]
![image](https://github.com/swoole/docker-swoole/assets/42090953/282fdb3a-3057-4b4a-aa93-3db810feddbe)

**Comment by deminy** [comment]
Hi there. I tried [example 00](https://github.com/swoole/docker-swoole/tree/master/examples/00-autoreload) and everything seems fine.

I'm wondering if you did have your local directory properly mounted to the Docker container started. To double check it, please

* make some file changes locally.
* log into the Docker container and check if files have been changed there as well.
