### ISSUE TITLE
install - PHP extendion like, php8.1-fpm, php8.1-common, php8.1-cli, php-pear

### ISSUE THREAD

**Issue by mchterence** [swoole/docker-swoole#43]
@deminy 

**And may i know how can i install other PHP extendion like, php8.1-fpm, php8.1-common, php8.1-cli, php-pear**
anyway can add in DockFile?

and cannot found /run/php/php8.1-fpm.sock in run folder? is it related not install? 

![image](https://github.com/swoole/docker-swoole/assets/19551612/24255876-8d54-45a0-97b5-fbf7e05e8ef8)

**Comment by deminy** [comment]
Hi there.

`1.` There is a section [How to Install More PHP Extensions](https://github.com/swoole/docker-swoole#how-to-install-more-php-extensions) in the README file explaining how to install PHP extensions. There is another section [More Examples](https://github.com/swoole/docker-swoole#more-examples) in the README file showing how to install and configure PHP extensions.

`2.` To serve HTTP traffic, you can choose to use PHP-FPM or Swoole, but not both. They don't work well together. Thus the Swoole images don't have PHP-FPM included.

`3.` PEAR is included by default:

```bash
docker run --rm phpswoole/swoole  which pear # The output is: /usr/local/bin/pear
```

Hope the answer helps.
