### ISSUE TITLE
Upgrade Alpine version and Fix Vulnerabilities in Image

### ISSUE THREAD

**Issue by vs0uz4** [swoole/docker-swoole#53]
Hello, when using the docker image `phpswoole/swoole:4.8-php8.2-alpine` I am getting information of vulnerabilities, when researching I discovered that these are vulnerabilities due to the `alpine` base image. Could we upgrade this image?

Vulnerabilities found in the Alpine base image (`php:8.2.3-cli-alpine3.16`) used in the `phpswoole/swoole:4.8-php8.2-alpine` image
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/07f7d8f9-c1a2-493e-83f2-e1078dc7f80d">

**Comment by deminy** [comment]
I will get it reviewed and merged this weekend. Thanks @vs0uz4.
